version: "3.8"

services: 
    jtl-shop:
        image: jtl-shop
        build: 
            context: ./docker/web
            args:
                PHP_VERSION: "${PHP_VERSION}"
                JTL_VERSION: "${JTL_VERSION}"
                TZ: Europe/Berlin
        ports: 
            - "80:80"
        depends_on: 
            - "jtl-db"

    
    jtl-db:
        image: mariadb:10
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            TZ: "Europe/Berlin"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        volumes: 
            - jtl_db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        ports: 
            - "8080:80"
        environment: 
            PMA_HOST: jtl-db
            TZ: "Europe/Berlin"
        depends_on: 
            - "jtl-db"

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8081:8025"
            - "1025:1025"

volumes: 
    jtl_db:



